name: spot-compare-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - jupyterlab
  - ipykernel
  - matplotlib
  - simpleitk
  - tifffile
  - scikit-image 
